### ISSUE TITLE
Бароны

### ISSUE THREAD

**Issue by sserov** [kst179/LoveLetter#3]
Возможно, стоит все-таки показывать карту того, кто выбил тебя бароном, чтобы все было честно.

**Comment by FortsAndMills** [comment]
В целом лишено смысла. Так выбитый игрок начинает обладать информацией, которую он может случайно спалить в общем чате, а такие опасности обычно минимизируют.

**Comment by sserov** [comment]
Но зато ты уверен, что игра работает честно и автор не мухлюет, например.
