### ISSUE TITLE
Стражницу должно быть можно использовать на себя

### ISSUE THREAD

**Issue by sserov** [kst179/LoveLetter#9]

**Comment by FortsAndMills** [comment]
щито, простите?

**Comment by sserov** [comment]
Можно угадывать карту у самого себя, разве нет? А в боте нельзя.

**Comment by sserov** [comment]
Окей, стражницу нельзя использовать на себя. В случае, если ни на кого нельзя применить, она должна уходить без эффекта.

**Comment by kst179** [comment]
Пока что можно функционалом игры показать всем, какой карты у тебя точно нет, по моему это классная фича (типа это фича а не баг).

**Comment by sserov** [comment]
Issue #9 не соответствует правилам игры.
